version: '3.9'

networks:
  front-tier:
  back-tier:

services:

  prediction-service:
    build: 
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "9696"
    ports:
      - "9696:9696"
    command: gunicorn --bind=0.0.0.0:9696 web_service:app

    networks:
      - back-tier

  monitoring-service:
    build: 
      context: ./monitoring
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - back-tier
    volumes:
      - './monitoring/dashboards:/app/dashboards'