version: '3.9'

networks:
  front-tier:
  back-tier:

services:

  prefect-server:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: prefect-server
    environment:
      TRACKING_SERVER_HOST: "34.16.139.230"
      TRACKING_SERVER_PORT: "5000"
      DATA_PATH: "https://storage.googleapis.com/mlflow-assignment-mj/training_data/day.csv"
      EXPERIMENT_NAME: "bike-sharing-regression"
      MODEL_REGISTRY_NAME: "random-forest-regressor"
      MODEL_SEARCH_ITERATIONS: "10"
    expose:
      - "4200"
    ports:
      - "127.0.0.1:4200:4200"
    command: prefect server start --host=0.0.0.0
    networks:
      - back-tier

  prediction-service:
    build: 
      context: ./app
      dockerfile: Dockerfile
    environment:
      RUN_ID: "79934c79a98f4932aade316cce6e61a0"
      TRACKING_SERVER_HOST: "34.16.139.230"
      TRACKING_SERVER_PORT: "5000"
      MODEL_NAME: "random-forest-regressor"

    expose:
      - "9696"
    ports:
      - "9696:9696"
    command: gunicorn --bind=0.0.0.0:9696 web_service:app

    networks:
      - back-tier

  monitoring-service:
    build: 
      context: ./monitoring
      dockerfile: Dockerfile
    environment:
      REFERENCE_DATA_PATH: "scored_reference.csv"
      CURRENT_DATA_PATH: "scored_current.csv"
      REPORT_PATH: "./dashboards/data_drift.html"
    ports:
      - "8001:8001"
    networks:
      - back-tier
    volumes:
      - './monitoring/dashboards:/app/dashboards'