[tool.pylint.messages_control]

disable = [
    "ungrouped-imports",
    "missing-module-docstring",
    "too-few-public-methods",
    "missing-final-newline",
    "bare-except",
    "no-name-in-module",
    "invalid-name",
    "duplicate-code",
    "too-many-return-statements", 
    "wildcard-import", 
    "unused-import", 
    "useless-return", 
    "line-too-long",
    "unused-wildcard-import", 
    "too-many-arguments",
    "unused-variable",
    "missing-timeout",
    "no-else-return",
    "redefined-outer-name"
]

[tool.black]
line-length = 200
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true